### ISSUE TITLE
No access to descendants-lib-39.tar.gz and descendants-lib-1024.tar.gz

### ISSUE THREAD

**Issue by ShaopuLin** [davidburrell/GRPS39#1]
When I tried downloading descendants-lib-39.tar.gz and descendants-lib-1024.tar.gz from https://www.dropbox.com/s/sphgl7zk123efdi/descendants-lib-1024.tar.gz?dl=0 and https://www.dropbox.com/s/sphgl7zk123efdi/descendants-lib-1024.tar.gz?dl=0, they ended with errors.
![error1](https://github.com/davidburrell/GRPS1024/assets/137581487/a5c42b68-8ea1-46fa-9918-a214cae09919)
![error2](https://github.com/davidburrell/GRPS1024/assets/137581487/ee5fd4b0-214a-436d-a08d-0125a46576e8)
It seems those 2 links aren't publicly accessible.

**Comment by davidburrell** [comment]
I've changed the permissions, give it another try and let me know.

**Comment by ShaopuLin** [comment]
Now those 2 files can be downloaded.
